---
- name: Deploy Docker container
  hosts: web
  become: true

  tasks:

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull application image
      command: docker pull parthh21/devops-demo:latest

    - name: Stop old container if exists
      command: docker rm -f devops-app
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name devops-app -p 8085:8080 parthh21/devops-demo:latest

